export const lessonConfig = {
  id: 'er-pronunciation',
  title: '法语字母“er”发音课程',
  targetPhonemes: ['/ɛr/'],
  coreSpellings: { '/ɛr/': ['er'] },
  ui: {
    optionAudio: true,
    submitRequired: true,
    shuffleOptions: true,
    speakingMode: 'fake',
    autoPlayExplanationVideo: false,
  },
  sequence: [
    {
      id: 'match-mer-fer',
      type: 'matching',
      prompt: '匹配发音及单词：',
      pairs: [
        { id: 'mer', word: 'mer', audio: 'mer' },
        { id: 'fer', word: 'fer', audio: 'fer' },
      ],
      correctSound: 'correct-speak',
      shuffle: true,
    },
    {
      id: 'explain-final-er',
      type: 'phoneme-explanation',
      grapheme: 'er',
      phoneme: '/ɛr/',
      explanation: '字母“er”，除了发音为 /e/ 之外，在一些较短的单音节词词尾，还会读作 /ɛr/，比如你刚刚见到的 mer、fer。',
      video: 'er-word-final-mouth-guide',
    },
    {
      id: 'choose-ter',
      type: 'binary-pronunciation-choice',
      prompt: '选出下列单词正确的发音：',
      word: { text: 'ter', audio: 'ter' },
      options: [
        { id: 'ter-correct', audio: 'ter', label: '/tɛr/', correct: true },
        { id: 'ter-te', audio: 'ter-distractor', label: '/te/', correct: false },
      ],
      shuffleOptions: true,
      submitRequired: true,
      correctSound: 'correct-speak',
    },
    {
      id: 'match-ferme-vertu',
      type: 'matching',
      prompt: '匹配发音及单词：',
      pairs: [
        { id: 'ferme', word: 'ferme', audio: 'ferme' },
        { id: 'vertu', word: 'vertu', audio: 'vertu' },
      ],
      correctSound: 'correct-speak',
      shuffle: true,
    },
    {
      id: 'explain-medial-er',
      type: 'spelling-family',
      phoneme: '/ɛr/',
      explanation: '除了单音节词词尾之外，字母“er”出现在词中时，通常也读作 /ɛr/。',
      items: [
        { grapheme: 'er', example: 'ferme', audio: 'ferme' },
        { grapheme: 'er', example: 'vertu', audio: 'vertu' },
      ],
    },
    {
      id: 'choose-perdu',
      type: 'binary-pronunciation-choice',
      prompt: '选出下列单词正确的发音：',
      word: { text: 'perdu', audio: 'perdu' },
      options: [
        { id: 'perdu-correct', audio: 'perdu', label: '/pɛʁdy/', correct: true },
        { id: 'perdu-pedu', audio: 'perdu-distractor', label: '/pedu/', correct: false },
      ],
      shuffleOptions: true,
      submitRequired: true,
      correctSound: 'correct-speak',
    },
    {
      id: 'confirm-er-pronunciation',
      type: 'phoneme-multiselect',
      targetPhoneme: '/ɛr/',
      options: [
        { text: 'parler', audio: 'parler', correct: false },
        { text: 'service', audio: 'service', correct: true },
        { text: 'cher', audio: 'cher', correct: true },
      ],
      shuffle: true,
      multiSelect: true,
      correctWords: ['service', 'cher'],
    },
    { id: 'speak-ver', type: 'speaking-practice', word: 'ver', ipa: '/vɛr/', targetGrapheme: 'er', audio: 'ver' },
    { id: 'speak-merci', type: 'speaking-practice', word: 'merci', ipa: '/mɛʁsi/', targetGrapheme: 'er', audio: 'merci' },
  ],
};
